### ISSUE TITLE
what is the project state ?

### ISSUE THREAD

**Issue by schmurfy** [dsully/circulardb#1]
Hi,
this is not really an issue but since I cannot send a private message...
I just found your project and was wondering which was its state, is it working ? is it abandoned ?

I started looking for an alternative to rrd nearly since I really started using rrd but there isn't a lot of options out there.

**Comment by dsully** [comment]
Hi there - it's not abandoned - just no recent updates. It's working as is. The biggest part that's lacking is documentation.

**Comment by schmurfy** [comment]
good to hear ! I can continue digging then :)
I managed to build it on my computer and tried to use it but as you pointed documentation is really lacking, I am trying to update the ruby plugins for 1.9 to give it a ride. I will send a pull request if I manage to make it works (it segfaults for now xD).

I was curious about the "basic stats", could you give me some informations ? (I did not look at the code yet, was waiting for your answer on the project's state)

**Comment by dsully** [comment]
Great - the Ruby extensions were written against 1.8, I've not been working in Ruby lately so I've not updated them.

What sort of basic stats are you looking for?

**Comment by schmurfy** [comment]
In the readme you said some basic stats are available, that si what I was refering to.
